### ISSUE TITLE
Test suite skipped due to failure to locate file

### ISSUE THREAD

**Issue by lauramcastro** [efene/efene#12]
I am unable to run the CT suite on efene, since it fails to locate the `ms.hrl` file sitting in the examples directory.

On a more "philosophical" level, I kind of think one should find a more suitable place for that file, since it is only used for testing...

**Comment by marianoguerra** [comment]
moved to test suite data folder and fixed in https://github.com/efene/efene/commit/33a77b251ecda099e4a77418c2abe5666697213f
