### ISSUE TITLE
Can't Build Efene

### ISSUE THREAD

**Issue by fribeiro1** [efene/efene#8]
I am getting the following error when building Efene:

    src/efene.erl:301: syntax error before: '{'
    src/efene.erl:59: function format_errors_or/3 undefined

Please advise.

**Comment by marianoguerra** [comment]
are you using erlang version < 17?

**Comment by fribeiro1** [comment]
I was, and the issue was fixed by the upgrade, thanks!

**Comment by marianoguerra** [comment]
no problem, feel free to open tickets or contact me for any doubt you have :)
